config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :uploads
  resources :images
  root to: 'images#index'
  get 'dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  default_scope { order('created_at DESC') }
  scope :is_private, -> { where(is_private: true) }
  scope :is_public, -> { where(is_private: false).or(where(is_private: nil)) }

  belongs_to :upload
  has_one_attached :file

  validates :title, :description, presence: true
  validates :title, length: { maximum: 30 }
  validates :description, length: { maximum: 160 }

  def download_image
    file.download
  end
end

app/models/upload.rb
# frozen_string_literal: true

class Upload < ApplicationRecord
  belongs_to :user
  has_many :images, inverse_of: 'upload'

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :uploads

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def index
    @private_images = Image.is_private.includes(:upload).where(
      'uploads.user_id = ?', @user
    ).references(:uploads).reorder(
      'images.created_at DESC'
    )
    @public_images = Image.is_public.includes(:upload).where(
      'uploads.user_id = ?', @user
    ).references(:uploads).reorder(
      'images.created_at DESC'
    )
  end

  private

  def set_user
    @user = current_user
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_image, only: %i[edit update destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.is_public
    respond_to do |format|
      format.html
      format.json { render json: { images: @images } }
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    redirect_to root_path, alert: 'Action not permitted' if current_user != @image.upload.user
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    return unless current_user == @image.upload.user

    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:title, :description, :is_private, :file)
  end
end

app/controllers/uploads_controller.rb
# frozen_string_literal: true

class UploadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_upload, only: %i[show edit update destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show; end

  # GET /uploads/new
  def new
    @upload = Upload.new
    @upload.images.build
  end

  # GET /uploads/1/edit
  def edit; end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)
    @upload.user = current_user

    respond_to do |format|
      if @upload.save
        format.html { redirect_to dashboard_path, notice: 'Upload was successful.' }
        format.json { render :show, status: :created, location: dashboard_path }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_upload
    @upload = Upload.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def upload_params
    params.require(:upload).permit(:id, images_attributes: %i[id title description is_private file])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id

    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("#{association.to_s.singularize}_fields", f: builder)
    end

    link_to(name, '#',
            class: 'add_fields column is-4 button is-outlined is-text is-inverted
            is-large has-text-weight-semibold has-text-success has-background-white',
            data: { id: id, fields: fields.gsub("\n", '') })
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/images_helper.rb
# frozen_string_literal: true

module ImagesHelper
end

app/helpers/uploads_helper.rb
# frozen_string_literal: true

module UploadsHelper
end

app/views/dashboard/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title has-text-grey">My Private Photos</h1>
    <% if @private_images.count.zero? %>
      <p class="content has-text-weight-light">You've not uploaded any private images.</p>
    <% else %>
      <div class="tile is-ancestor">
        <div class="tile is-parent is-flex-wrap-wrap">
          <% @private_images.each do |image| %>
            <div class="tile is-child is-4 box is-shadowless" data-text-search-target="image">
              <div class="columns">
                <div class="column is-12">
                  <figure class="image is-4by3">
                    <%= link_to(image_tag(image.file.variant(gravity: 'center', resize_to_limit: [400,nil], crop: '400x300+0+0')), image) if image.file.attached? %>
                  </figure>
                  <br>
                  <p class="content is-marginless has-text-weight-semibold is-small"><%= image.title %></p>
                  <p class="content has-text-weight-light is-small"><%= image.description.truncate(50) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <div class="container">
    <h1 class="title has-text-grey">My Public Photos</h1>
    <% if @public_images.count.zero? %>
      <p class="content has-text-weight-light">You've not uploaded any public images.</p>
    <% else %>
      <div class="tile is-ancestor">
        <div class="tile is-parent is-flex-wrap-wrap">
          <% @public_images.each do |image| %>
            <div class="tile is-child is-4 box is-shadowless" data-text-search-target="image">
              <div class="columns">
                <div class="column is-12">
                  <figure class="image is-4by3">
                    <%= link_to(image_tag(image.file.variant(gravity: 'center', resize_to_limit: [400,nil], crop: '400x300+0+0')), image) if image.file.attached? %>
                  </figure>
                  <br>
                  <p class="content is-marginless has-text-weight-semibold is-small"><%= image.title %></p>
                  <p class="content has-text-weight-light is-small"><%= image.description.truncate(50) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</section>

app/views/images/_form.html.erb
<section class="section">
  <div class="container">
    <%= form_with(model: image, local: true) do |form| %>
      <% if image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>
          <ul>
            <% image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="columns is-centered">
        <div class="column is-4">
          <%#  %>
          <div class="field">
            <div class="file has-name is-small is-fullwidth">
              <label class="file-label">
                <span style="display:none;">
                  <%= form.file_field :file,
                      "data-action": "change->image-uploader#changeFileName", id: "#{form.index}-file-name" %>
                </span>
                <span class="file-cta">
                  <span class="file-icon">
                    <i class="fas fa-upload"></i>
                  </span>
                  <span class="file-label">
                    Choose a file…
                  </span>
                </span>
              </span>
            </label>
          </div>
        </div>
        <%#  %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <%= form.text_field :title, class: "input", placeholder: "Title", required: true %>
        </div>
        <div class="field">
          <%= form.label :description, class: "label" %>
          <%= form.text_area :description, class: "textarea", placeholder: "Description", rows: 3, required: true %>
        </div>
        <br>
        <div class="actions">
          <%= form.submit class: 'button is-fullwidth is-info' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</section>

app/views/images/edit.html.erb
<section class="section">
  <div class="container">
    <h2 class="subtitle has-text-weight-semibold">Editing Image</h2>
  </div>
</section>
<%= render 'form', image: @image %>
<section class="section">
  <div class="container">
    <%= link_to 'Show', @image %> |
    <%= link_to 'Back', images_path %>
  </div>
</section>

app/views/images/index.html.erb
<section data-controller="text-search" data-text-search-hidden-class="is-hidden">
  <section class="hero is-light is-small">
    <div class="hero-body">
      <div class="container">
        <h1 class="title is-size-1 has-text-weight-bold">
          AbuleShoots
        </h1>
        <h2 class="subtitle">
          Store, share and discover rustic images.<br>
          Contributed by creators like you.
        </h2>
        <div class="columns">
          <div class="column is-6">
            <div class="field">
              <div class="control is-expanded">
                <%= text_field_tag 'query', "", placeholder: 'Search free rustic images', 
          type: 'search', class: 'input is-large', 'data-text-search-target': 'filterInput',
          'data-action': 'input->text-search#filter' %>
              </div>
            </div>
          </div>
        </div>
        <p class="help is-hidden"><strong>Categories:</strong> earth, water, forest, people, play</p>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="container">
      <div class="tile is-ancestor">
        <div class="tile is-parent is-flex-wrap-wrap">
          <% @images.each do |image| %>
            <div class="tile is-child is-4 box is-shadowless" data-text-search-target="image">
              <div class="columns">
                <div class="column is-12">
                  <figure class="image is-4by3">
                    <%= link_to(image_tag(image.file.variant(gravity: 'center', resize_to_limit: [400,nil], crop: '400x300+0+0')), image) if image.file.attached? %>
                  </figure>
                  <br>
                  <p class="content is-marginless has-text-weight-semibold is-small"><%= image.title %></p>
                  <p class="content has-text-weight-light is-small"><%= image.description.truncate(50) %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</section>

app/views/images/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="subtitle">Submit a photo</h1>
  </div>
</section>
<section class="section">
  <div class="container">
    <%= render 'form', image: @image %>
    <%= link_to 'Back', images_path %>
  </div>
</section>

app/views/images/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4-tablet is-3-desktop is-3-widescreen">
        <%# The sidebar %>
        <p class="title is-size-4"><%= @image.title %></p>
        <div class="content">
          <%= @image.description %>
        </div>
        <hr class="divider">
        <% if @image.file.attached? %>
          <div class="buttons">
            <%= link_to "Download free photo", rails_blob_path(@image.file, disposition: 'preview'), class: "button is-info has-text-weight-bold", target: :_blank %>
          </div>
        <% end %>
        <hr class="divider">
        <p><strong>Photo by: </strong><%= @image.upload.user.name %></p>
        <br>
        <p class="is-hidden"><strong>Category:</strong> <br>
          business, laptop, office, computer, keyboard, technology</p>
      </div>
      <div class="column">
        <%# The right part for the image %>
        <div class="card has-background-grey">
          <div class="card-image">
            <figure class="image">
              <%= image_tag @image.file if @image.file.attached? %>
            </figure>
          </div>
        </div>
        <br>
        <% if current_user === @image.upload.user %>
          <%= link_to 'Edit', edit_image_path(@image), class: "button is-info has-text-white" %>
        <% end %>
        <%= link_to 'Back', images_path, class: "button is-dark" %>
        <br>
        <br>
        <div class="container is-hidden">
          <p class="subtitle">Similar images</p>
          <div class="container">
            <div class="columns is-mobile">
              <div class="column is-3">
                <figure class="image is-128x128">
                  <img src="https://bulma.io/images/placeholders/256x256.png">
                </figure>
              </div>
              <div class="column is-3">
                <figure class="image is-128x128">
                  <img src="https://bulma.io/images/placeholders/256x256.png">
                </figure>
              </div>
              <div class="column is-3">
                <figure class="image is-128x128">
                  <img src="https://bulma.io/images/placeholders/256x256.png">
                </figure>
              </div>
              <div class="column is-3">
                <figure class="image is-128x128">
                  <img src="https://bulma.io/images/placeholders/256x256.png">
                </figure>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <p>AbuleShoots</p>
      </a>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="">
            <%= link_to 'Submit a photo', new_upload_path, class: 'button is-success' %>
          </div>
        </div>
        <% unless user_signed_in? %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to 'Login', new_user_session_path, class: 'button is-white' %>
              <%= link_to 'Join free', new_user_registration_path, class: 'button is-light' %>
            </div>
          </div>
        <% else %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to 'My Photos', dashboard_path, class: 'button is-text-grey has' %>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "button is-white has-text-grey" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_notice.html.erb
<div class="container">
  <% if notice %>
    <p class="notice notification is-grey mb-2">
      <button class="delete"></button>
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p class="alert notification is-warning is-light mb-2">
      <button class="delete"></button>
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AbuleShoots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notice' %>
    <%= yield %>
  </body>
</html>

app/views/uploads/_form.html.erb
<section data-controller='image-uploader'>
  <%= form_with(model: upload, local: true) do |f| %>
    <% if upload.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>
        <ul>
          <% upload.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="columns is-multiline is-vcentered">
      <%= f.fields_for :images do |f| %>
        <%= render "image_fields", f: f %>
      <% end %>
      <%= link_to_add_fields "Add more", f, :images %>
    </div>
    <div class="columns">
      <div class="column is-4">
        <div class="actions">
          <%= f.submit "Upload", class: "button is-success is-fullwidth has-text-weight-semibold" %>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/uploads/_image_fields.html.erb
<div class="column is-4">
  <div class="field">
    <div class="file has-name is-small is-fullwidth">
      <label class="file-label">
        <span style="display:none;">
          <%= f.file_field :file,
                      "data-action": "change->image-uploader#changeFileName", id: "#{f.index}-file-name" %>
        </span>
        <span class="file-cta">
          <span class="file-icon">
            <i class="fas fa-upload"></i>
          </span>
          <span class="file-label">
            Choose a file…
          </span>
        </span>
        <span class="file-name" data-image-uploader-target="textToChange" id="<%= f.index %>-file-name">
          No image selected
        </span>
      </label>
    </div>
  </div>
  <div class="field">
    <%= f.text_field :title, class: "input is-small", placeholder: "Image title" %>
  </div>
  <div class="field">
    <%= f.text_area :description, class: "textarea is-small", placeholder: "Small note of 160 charaters limit", rows: 3 %>
  </div>
  <div class="field">
    <span class="help">
      <%= f.check_box :is_private, {}, true, false %> Make private
    </span>
  </div>
</div>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploads</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="subtitle has-text-weight-bold">Upload images</h1>
  </div>
</section>
<section class="section">
  <div class="container">
    <%= render 'form', upload: @upload %>
    <div class="columns">
      <div class="column is-4">
        <%= link_to 'Back', uploads_path, class: "button is-fullwidth has-text-weight-semibold" %>
      </div>
    </div>
  </div>
</section>

app/views/uploads/show.html.erb
<% @upload.images.each do |image| %>
  <%= image.title %>
  <%= image.description %>
  <%= image_tag(image.file) if image.file.attached? %>
<% end %>
<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "button is-fullwidth is-text has-background-white" %>
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "button is-fullwidth is-text has-background-white" %>
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "button is-fullwidth is-text has-background-white" %>
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "button is-fullwidth is-text has-background-white" %>
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "button is-fullwidth is-text has-background-white" %>
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "button is-fullwidth is-text has-background-white" %><br />
  <% end %>
<% end %>